### ISSUE TITLE
0.04 tarball looks incomplete

### ISSUE THREAD

**Issue by eserte** [nrdvana/perl-Tree-RB-XS#1]
See https://metacpan.org/release/NERDVANA/Tree-RB-XS-0.04 --- no pm file, no xs file.

**Comment by nrdvana** [comment]
I'm about to upload another one.  Oddly the tar.gz on my local disk is complete and installable, so somehow it got cut off during the upload.  Never had that happen before.

**Comment by nrdvana** [comment]
Version 0.05 is released.
