### ISSUE TITLE
"failed to extend arg stack" with perls with -DDEBUGGING in ccflags

### ISSUE THREAD

**Issue by andk** [nrdvana/perl-Tree-RB-XS#2]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/8f375f10-e019-11ec-b7f4-2653d23cd8a8

**Comment by nrdvana** [comment]
I'm totally stumped by this one.  I'm asking on perlmonks:  https://www.perlmonks.org/?node_id=11144355

**Comment by nrdvana** [comment]
This bug only affects perls with debugging enabled.  (therefore, an "antiheisenbug", since it only shows up when debugging is *enabled*)

Reported to perl core at https://github.com/Perl/perl5/issues/19818

**Comment by nrdvana** [comment]
Fixed in version 0.07, just released to CPAN
