### ISSUE TITLE
 Object lacks 'struct TreeRBXS' magic after dclone

### ISSUE THREAD

**Issue by gimme00** [nrdvana/perl-Tree-RB-XS#3]
This is a great implementation of RB tree with lost of features. I have been using it successfully, but recently ran into a problem trying to serialise or dclone the tree object. `dclone $tree` works, but when trying to use the cloned object I get `Object lacks 'struct TreeRBXS' magic` error. Unfortunately, my XS is not up to scratch yet to fix this.

To reproduce:

```perl
#!/usr/bin/env perl

use Tree::RB::XS;
use Storable qw(dclone);

my $tree = Tree::RB::XS->new( compare_fn => CMP_FLOAT, allow_duplicates => 1);

$tree->put(rand() => 1) for 1..10;
print "size of tree = " . $tree->size . "\n";
# size of tree = 10

my $cloned_tree = dclone $tree;
print "size of $cloned_tree = " . $cloned_tree->size . "\n";
# Object lacks 'struct TreeRBXS' magic at tree_clone.pm line 13.
# Command terminated with non-zero status.
```

**Comment by nrdvana** [comment]
Glad someone is getting good use from it :-)  Pretty much every XS module that stores data will need custom Storable hooks, and I haven't implemented that at all.  The best implementation would be in XS, but you could add them as pure-perl too.  I won't have time to get to this for quite a while (work is fairly busy right now) but you could do a basic serialization like:

```
sub Tree::RB::XS::STORABLE_freeze($self, $cloning) {
  my $iter= $self->iter;
  my @node_data;
  while (!$iter->done) { push @node_data, $iter->next_kv }
  return $self->VERSION,
    [ $self->compare_fn, $self->allow_duplicates, $self->compat_list_get ],
    \@node_data
}
```

and then deserialize that like

```
sub Tree::RB::XS::STORABLE_thaw($self, $cloning, $version, $attrs, $nodes) {
  $self->_init_tree(undef, $attrs->[0]);
  $self->allow_duplicates($attrs->[1]);
  $self->compat_list_get($attrs->[2]);
  for (my $i= 0; $i < @$nodes; $i+= 2) {
    $self->put($nodes->[$i], $nodes->[$i+1]);
  }
}
```

I haven't tested this, but hopefully it gets you started.  Let me know how it goes.

**Comment by gimme00** [comment]
I was thinking something along these lines, but this solution is way ahead of what I have so far. Will try this!

**Comment by gimme00** [comment]
After some tiny tweaks and the solution worked fine as suggested.

After I do some more extensive testing, would you ~~accept~~ consider a PR with the pure perl code for this package? It may be a good interim solution until XS solution is available.

**Comment by nrdvana** [comment]
Sure, I'm fine with a pure perl implementation for now.

**Comment by nrdvana** [comment]
The module now serializes as long as you're using a built-in compare function, but it can also 'dclone' if you use a global-named custom compare function.  The Node objects can also serialize, but the iterators can't.  (seems to be a Storable limitation that it can't handle blessed coderefs)
